### ISSUE TITLE
mhtが読めないです

### ISSUE THREAD

**Issue by kazuhirox** [Yottwui0911/ObjectOrientedProgramingSkillUp#4]
ドラえもん～mhtが読めないよ～

IE/Chromeともに開けないですけど、なにかコツがありますか？

**Comment by Yottwui0911** [comment]
@kazuhirox 私はIEで開いていますがIEのバージョンはいくつでしょうか？

**Comment by Yottwui0911** [comment]
@kazuhirox zipから解凍すると読めなさそうです。localにcloneすることはできませんでしょうか？
pdfにすることも考えたんですが、変なとこで改ページ走って区切られてしまうんですよね。。。

**Comment by Yottwui0911** [comment]
@kazuhirox 修正したコミットをマージしました！mhtファイルではちょっと厳しそうでしたので、htmlファイルを作成いたしました。ご確認ください。

**Comment by kazuhirox** [comment]
ありがとうございます。htmlで読めました！
ちなみに、Windows10のIE11(v11.0.100)でした。

**Comment by Yottwui0911** [comment]
@kazuhirox 確認ありがとうございます！
